#!/usr/bin/env bash
# This code write by Mr.nope
# Black-Tool v5.0.0
if [[ "$(id -u)" -ne 0 ]]; then
  echo "
Please, Run This Programm as Root!
"
  exit 1
fi
function main() {
       clear
       echo "
Updating...
"
       sleep 2
       cd .. && cd .. && sudo rm -r Black-Tool && git clone https://github.com/mrprogrammer2938/Black-Too/usr/bin && rm hack && cd /usr/local/bin && rm hack
       l && cd echo "
Updating..., Finish...!
"
       exit 1
}
main
